### ISSUE TITLE
Pick a design

### ISSUE THREAD

**Issue by brentmclark** [chadlof/react-to-do-list#10]
- [x] Pick a general site layout
- [x] Pick a color scheme.

**Comment by brentmclark** [comment]
What do you think about this one?  Potentially change the colors?

https://freewebsitetemplates.com/preview/frozenyogurtshop/index.html

**Comment by chadlof** [comment]
I like both the second and third option. 
Yep,I can for sure work with these!

**Comment by brentmclark** [comment]
Here's a random color scheme that looked flashy enough to be effective, but muted and boring enough to not get in the way.  Thoughts?  

https://coolors.co/b8bdd1-5a6d96-ff9244-fffef9-ff6b90

If you want to try something else, load up that link and keep hitting the `space` bar until you're satisfied.

**Comment by brentmclark** [comment]
Here's the one we worked on together. 

https://coolors.co/b8bdd1-5a6d96-ff9244-a49e8d-8ad3d9

**Comment by brentmclark** [comment]
And the winners are:

Theme: https://freewebsitetemplates.com/preview/zerotype/index.html
Color Palette: https://coolors.co/b8bdd1-5a6d96-ff9244-a49e8d-8ad3d9

**Comment by chadlof** [comment]
I started playing around with our color scheme. I changed the first color to be a little lighter. 
https://coolors.co/dcd6f7-5a6d96-ff9244-a49e8d-8ad3d9

I'll push up what I have, let me know what you think. 
I'm open to any changes!
